### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pkerpedjiev** [danielrozenberg/httpfs#3]
Hi, thanks for making this repo available. I just wanted to ask if it's released under a particular license?

I would like to use it within the MIT-licensed [higlass-server](https://github.com/higlass/higlass-server/) project and want to make sure that doing so is permitted.

There's also a few changes I could contribute back to the repo.

**Comment by danielrozenberg** [comment]
🙈🙈🙈 turns out I disabled notifications for this repo by accident and only noticed it just now! I added an ISC license. I guess this is probably no longer relevant, but thanks for the reminder that I should add one. Sorry for taking almost two years to do that 🙈

**Comment by pkerpedjiev** [comment]
Lol. Thank you!

The license uncertainty led me to start a very similar project here (with attribution to you): https://github.com/higlass/simple-httpfs

**Comment by danielrozenberg** [comment]
Oh cool! I'll link to it from my README since it looks like you actively maintain your project :)

**Comment by pkerpedjiev** [comment]
Great! I appreciate it.
